using System.Collections.Generic;

namespace CardonerSistemas.Framework.Afip
{
    public partial class Tablas
    {
        public const string MonedaPesos = "PES";

        public enum ConceptosComprobantes : byte
        {
            Productos = 1,
            Servicios = 2,
            ProductosYServicios = 3,
            Otro = 4
        }

        public static readonly Dictionary<string, string> Monedas = new Dictionary<string, string>()
        {
            { "000", "otras monedas" },
            { "PES", "pesos" },
            { "DOL", "dólar estadounidense" },
            { "002", "dólar eeuu libre" },
            { "003", "francos franceses" },
            { "004", "liras italianas" },
            { "005", "pesetas" },
            { "006", "marcos alemanes" },
            { "007", "florines holandeses" },
            { "008", "francos belgas" },
            { "009", "francos suizos" },
            { "010", "pesos mejicanos" },
            { "011", "pesos uruguayos" },
            { "012", "real" },
            { "013", "escudos portugueses" },
            { "014", "coronas danesas" },
            { "015", "coronas noruegas" },
            { "016", "coronas suecas" },
            { "017", "chelines autriacos" },
            { "018", "dólar canadiense" },
            { "019", "yens" },
            { "021", "libra esterlina" },
            { "022", "marcos finlandeses" },
            { "023", "bolivar (venezolano)" },
            { "024", "corona checa" },
            { "025", "dinar (yugoslavo)" },
            { "026", "dólar australiano" },
            { "027", "dracma (griego)" },
            { "028", "florin (antillas hola" },
            { "029", "guarani" },
            { "030", "shekel (israel)" },
            { "031", "peso boliviano" },
            { "032", "peso colombiano" },
            { "033", "peso chileno" },
            { "034", "rand (sudafricano)" },
            { "035", "nuevo sol peruano" },
            { "036", "sucre (ecuatoriano)" },
            { "040", "lei rumanos" },
            { "041", "derechos especiales de giro" },
            { "042", "pesos dominicanos" },
            { "043", "balboas panameñas" },
            { "044", "cordobas nicaragûenses" },
            { "045", "dirham marroquíes" },
            { "046", "libras egipcias" },
            { "047", "riyals sauditas" },
            { "048", "brancos belgas financieras" },
            { "049", "gramos de oro fino" },
            { "050", "libras irlandesas" },
            { "051", "dólar de hong kong" },
            { "052", "dólar de singapur" },
            { "053", "dólar de jamaica" },
            { "054", "dólar de taiwan" },
            { "055", "quetzal (guatemaltecos)" },
            { "056", "forint (hungria)" },
            { "057", "baht (tailandia)" },
            { "058", "ecu" },
            { "059", "dinar kuwaiti" },
            { "060", "euro" },
            { "061", "zltys polacos" },
            { "062", "rupias hindúes" },
            { "063", "lempiras hondureñas" },
            { "064", "yuan (rep. pop. china)" }
        };


        public static readonly Dictionary<short, string> TiposComprobante = new Dictionary<short, string>()
        {
            { 1, "facturas A" },
            { 2, "notas de débito A" },
            { 3, "notas de crédito A" },
            { 4, "recibos A" },
            { 5, "notas de venta al contado A" },
            { 6, "facturas B" },
            { 7, "notas de débito B" },
            { 8, "notas de crédito B" },
            { 9, "recibos B" },
            { 10, "notas de venta al contado B" },
            { 11, "facturas C" },
            { 12, "notas de débito C" },
            { 13, "notas de crédito C" },
            { 15, "recibos C" },
            { 16, "notas de venta al contado C" },
            { 17, "liquidación de servicios públicos clase A" },
            { 18, "liquidación de servicios públicos clase B" },
            { 19, "facturas de exportación" },
            { 20, "notas de débito por operaciones con el exterior" },
            { 21, "notas de crédito por operaciones con el exterior" },
            { 22, "facturas - permiso exportación simplificado - Dto. 855/97" },
            { 23, "comprobantes “A” de compra primaria para el sector pesquero marítimo" },
            { 24, "comprobantes “A” de consignacion primaria para el sector pesquero marítimo" },
            { 25, "comprobantes “B” de compra primaria para el sector pesquero marítimo" },
            { 26, "comprobantes “B” de consignación primaria para el sector pesquero marítimo" },
            { 27, "liquidación única comercial impositiva clase A" },
            { 28, "liquidación única comercial impositiva clase B" },
            { 29, "liquidación única comercial impositiva clase C" },
            { 30, "comprobantes de compra de bienes usados" },
            { 31, "mandato - consignación" },
            { 32, "comprobantes para reciclar materiales" },
            { 33, "liquidación primaria de granos" },
            { 34, "comprobantes A del apartado a inciso f) R.G. n° 1415" },
            { 35, "comprobantes B del anexo i, apartado a, inc. f), R.G. n° 1415" },
            { 36, "comprobantes C del anexo i, apartado a, inc.f), R.G. n° 1415" },
            { 37, "notas de débito o documento equivalente que cumplan con la R.G. n° 1415" },
            { 38, "notas de crédito o documento equivalente que cumplan con la R.G. n° 1415" },
            { 39, "otros comprobantes A que cumplen con la r g 1415" },
            { 40, "otros comprobantes B que cumplan con la R.G. n° 1415" },
            { 41, "otros comprobantes C que cumplan con la R.G. n° 1415" },
            { 43, "nota de crédito liquidación única comercial impositiva clase B" },
            { 44, "nota de crédito liquidación única comercial impositiva clase C" },
            { 45, "nota de débito liquidación única comercial impositiva clase A" },
            { 46, "nota de débito liquidación única comercial impositiva clase B" },
            { 47, "nota de débito liquidación única comercial impositiva clase C" },
            { 48, "nota de crédito liquidación única comercial impositiva clase A" },
            { 49, "comprobantes de compra de bienes no registrables a consumidores finales" },
            { 50, "recibo factura a régimen de factura de crédito" },
            { 51, "facturas M" },
            { 52, "notas de débito M" },
            { 53, "notas de crédito M" },
            { 54, "recibos M" },
            { 55, "notas de venta al contado M" },
            { 56, "comprobantes M del anexo i apartado a inc f) R.G. n° 1415" },
            { 57, "otros comprobantes M que cumplan con la R.G. n° 1415" },
            { 58, "cuentas de venta y liquido producto M" },
            { 59, "liquidaciónes M" },
            { 60, "cuentas de venta y liquido producto A" },
            { 61, "cuentas de venta y liquido producto B" },
            { 63, "liquidaciónes A" },
            { 64, "liquidaciónes B" },
            { 66, "despacho de importación" },
            { 68, "liquidación C" },
            { 70, "recibos factura de crédito" },
            { 80, "informe diario de cierre (zeta) - controladores fiscales" },
            { 81, "tique factura A" },
            { 82, "tique factura B" },
            { 83, "tique" },
            { 88, "remito electrónico" },
            { 89, "resumen de datos" },
            { 90, "otros comprobantes - documentos exceptuados - notas de crédito" },
            { 91, "remitos r" },
            { 99, "otros comprobantes que no cumplen o están exceptuados de la R.G. 1415 y sus modif" },
            { 110, "tique nota de crédito" },
            { 111, "tique factura C" },
            { 112, "tique nota de crédito A" },
            { 113, "tique nota de crédito B" },
            { 114, "tique nota de crédito C" },
            { 115, "tique nota de débito A" },
            { 116, "tique nota de débito B" },
            { 117, "tique nota de débito C" },
            { 118, "tique factura M" },
            { 119, "tique nota de crédito M" },
            { 120, "tique nota de débito M" },
            { 201, "factura de crédito electrónica mipymes (FCE) A" },
            { 202, "nota de débito electrónica mipymes (FCE) A" },
            { 203, "nota de crédito electrónica mipymes (FCE) A" },
            { 206, "factura de crédito electrónica mipymes (FCE) B" },
            { 207, "nota de débito electrónica mipymes (FCE) B" },
            { 208, "nota de crédito electrónica mipymes (FCE) B" },
            { 211, "factura de crédito electrónica mipymes (FCE) C" },
            { 212, "nota de débito electrónica mipymes (FCE) C" },
            { 213, "nota de crédito electrónica mipymes (FCE) C" },
            { 331, "liquidación secundaria de granos" },
            { 332, "certificación electrónica (granos)" },
            { 995, "remito electrónico cárnico" }
        };

        public static readonly Dictionary<byte, string> TiposDocumento = new Dictionary<byte, string>()
        {
            { 0, "CI policía federal" },
            { 1, "CI Buenos Aires" },
            { 2, "CI Catamarca" },
            { 3, "CI Córdoba" },
            { 4, "CI Corrientes" },
            { 5, "CI Entre Ríos" },
            { 6, "CI Jujuy" },
            { 7, "CI Mendoza" },
            { 8, "CI La Rioja" },
            { 9, "CI Salta" },
            { 10, "CI San Juan" },
            { 11, "CI San Luis" },
            { 12, "CI Santa Fe" },
            { 13, "CI Santiago del Estero" },
            { 14, "CI Tucumán" },
            { 16, "CI Chaco" },
            { 17, "CI Chubut" },
            { 18, "CI Formosa" },
            { 19, "CI Misiones" },
            { 20, "CI Neuquén" },
            { 21, "CI La Pampa" },
            { 22, "CI Río Negro" },
            { 23, "CI Santa Cruz" },
            { 24, "CI Tierra del Fuego" },
            { 80, "CUIT" },
            { 86, "CUIL" },
            { 87, "CDI" },
            { 89, "LE" },
            { 90, "LC" },
            { 91, "CI extranjera" },
            { 92, "en trámite" },
            { 93, "acta nacimiento" },
            { 94, "pasaporte" },
            { 95, "CI Bs. As. RNP" },
            { 96, "DNI" },
            { 99, "sin identificar/venta global diaria" },
            { 30, "certificado de migración" },
            { 88, "usado por anses para padrón" }
        };

    }
}